[package]
name = "dbus-message-parser"
version = "2.2.0"
edition = "2018"
description = "Libary to encode and decode DBus message"
readme = "README.md"
authors = ["LinkTed <link.ted@mailbox.org>"]
license = "LGPL-3.0"
keywords = ["dbus", "parser"]
include = [
    "src/**/*.rs",
    "tests/*.rs",
    "examples/*.rs", 
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "NOTICE"
    ]
repository = "https://github.com/LinkTed/dbus-message-parser"
categories = [
    "parser-implementations",
    "encoding"
    ]

[dependencies]
bytes = "0.5.4"
regex = "1.3.9"
lazy_static = "1.4.0"
num-derive = "0.3.0"
num-traits = "0.2.11"
bitflags = "1.2.1"
